### ISSUE TITLE
im blockly kann keine variable als text eingefügt werden

### ISSUE THREAD

**Issue by krobipd** [klein0r/ioBroker.lametric#14]
bin gerade dabei meine skripte auf dein plugin umzustellen.

dabei ist mir aufgefallen ich kann beim blocky keine variable als text anhängen.

also wenn ich versuche meine text variable an die Meldung zu knüpfen wird das nicht akzeptiert. ich kann nicht das nicht speichern und beim neu laden ist die variable nicht verbunden.
<img width="617" alt="Bildschirmfoto 2019-10-25 um 17 16 39" src="https://user-images.githubusercontent.com/27220902/67583152-54deb480-f74b-11e9-95fc-484e2e71b57d.png">

**Comment by sanstarr** [comment]
same Problem here. It is not possible to add a variable (string, text) to lametric in blockly anymore.
if you try to add text to the lametric blocky, you can not save the script in iobroker...
please fix it. thank you!!!

**Comment by j0hu** [comment]
Hallo Matthias,

ich kann auch das oben genannte Problem feststellen (Script mit LaMetric-Modul und Variable als Text lässt sich nicht speichern). 

Vielleicht ist es Dir trotz Hausbau möglich, einen kurzen Blick darauf zu werfen :-) 
Evtl. lässt sich das Problem schnell beseitigen...

Vielen Dank vorab!

**Comment by klein0r** [comment]
So, in Version 0.0.7 sollte das wieder gehen. Sorry für die Verwirrung 😢
