### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by spoeh-man** [klein0r/ioBroker.lametric#148]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (used the search)
- [X] This issue is not described in the adapter documentation / FAQ

### LaMetric Firmware version

3.0.18

### The problem

Seit dem Update auf 3.1.0 immer folgende Fehler unter 3.0.0 läuft alles wie gewohnt.

host.ioBroker | 2023-10-26 12:04:47.751 | error | Caught by controller[1]: at Array.map (<anonymous>)
-- | -- | -- | --
host.ioBroker | 2023-10-26 12:04:47.751 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.lametric/main.js:1561:43
host.ioBroker | 2023-10-26 12:04:47.751 | error | Caught by controller[1]: at String.replace (<anonymous>)
host.ioBroker | 2023-10-26 12:04:47.751 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.lametric/main.js:1562:94
host.ioBroker | 2023-10-26 12:04:47.750 | error | Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'val')
host.ioBroker | 2023-10-26 12:04:47.749 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
lametric.0 | 2023-10-26 12:04:47.115 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
lametric.0 | 2023-10-26 12:04:47.112 | info | terminating
lametric.0 | 2023-10-26 12:04:47.087 | error | Cannot read properties of undefined (reading 'val')
lametric.0 | 2023-10-26 12:04:47.087 | error | TypeError: Cannot read properties of undefined (reading 'val') at /opt/iobroker/node_modules/iobroker.lametric/main.js:1562:94 at String.replace (<anonymous>) at /opt/iobroker/node_modules/iobroker.lametric/main.js:1561:43 at Array.map (<anonymous>) at LaMetric.refreshMyDataDiy (/opt/iobroker/node_modules/iobroker.lametric/main.js:1560:14) at /opt/iobroker/node_modules/iobroker.lametric/main.js:1551:18
lametric.0 | 2023-10-26 12:04:47.081 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'val')
lametric.0 | 2023-10-26 12:04:47.080 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
lametric.0 | 2023-10-26 12:04:46.502 | info | Starting - connecting to http://192.168.179.85:8080
lametric.0 | 2023-10-26 12:04:46.438 | info | starting. Version 3.1.0 in /opt/iobroker/node_modules/iobroker.lametric, node: v18.17.1, js-controller: 5.0.14

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

 5.0.14

### Version of Adapter

3.1.0

### Operating system running ioBroker

Linux

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by tmaul1968** [comment]
Das ist kein Einzelfall.
Tritt bei mir exakt genauso auf, bin auf 3.0.0 zurück gegangen.
Gleiches SetUp (current beta) und dieselben log Einträge.

**Comment by tomschlde** [comment]
hab noch ne Info:

`lametric has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"iconPosition"},"message":"must NOT have additional properties"}]`

**Comment by tmaul1968** [comment]
Mit v3.1.1 ist das Thema bei mir erledigt ;-)
Schnell gefixt, danke!!!

**Comment by spoeh-man** [comment]
Mit 3.1.1 erledigt Vielen Dank
