### ISSUE TITLE
Fehler 404 not found app

### ISSUE THREAD

**Issue by spoeh-man** [klein0r/ioBroker.lametric#152]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (used the search)
- [X] This issue is not described in the adapter documentation / FAQ

### LaMetric Firmware version

3.0.18

### The problem

Ich habe sehr oft folgende Fehler im Log

`

lametric.0 | 2023-11-07 12:15:53.523 | warn | (widget/update/com.lametric.diy.devwidget/xxxxxxxxxxxxxxxx) Unable to execute action: AxiosError: Request failed with status code 404
-- | -- | -- | --
lametric.0 | 2023-11-07 12:15:53.523 | warn | received 404 response from http://192.168.179.85:8080/api/v2/widget/update/com.lametric.diy.devwidget/xxxxxxxxxxxxx with content: {"errors":[{"message":"Not found app"}]}

`

Nachts bzw wenn es Dunkel ist auch immer wieder Fehler von ähnlichem Bild aber mit der Meldung 

`

lametric.0 | 2023-11-07 12:46:42.385 | warn | (device/notifications) Unable to execute action: AxiosError: Request failed with status code 400
-- | -- | -- | --
lametric.0 | 2023-11-07 12:46:42.385 | warn | received 400 response from http://192.168.179.85:8080/api/v2/device/notifications with content: {"errors":[{"message":"Only notifications with priority 'critical' are allowed in current mode"}]}

`

### Version of nodejs

18.17.1

### Version of ioBroker js-controller

5.0.16

### Version of Adapter

3.1.1

### Operating system running ioBroker

Linux on Proxmox

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by spoeh-man** [comment]
Gerade noch gesehen auch der Javascript adapter gibt dann einen fehler aus

`

javascript.0 | 2023-11-07 12:46:42.571 | error | script.js.common.Briefkasten.Lametricbenachrichtigung: {'message':'Request failed with status code 400','name':'AxiosError','stack':'AxiosError: Request failed with status code 400\n at settle (/opt/iobroker/node_modules/iobroker.lametric/node_modules/axios/lib/core/settle.js:19:12)\n at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.lametric/node_modules/axios/lib/adapters/http.js:572:11)\n at IncomingMessage.emit (node:events:526:35)\n at IncomingMessage.emit (node:domain:489:12)\n at endReadableNT (node:internal/streams/readable:1359:12)\n at processTicksAndRejections (node:internal/process/task_queues:82:21)','config':{'transitional':{'silentJSONParsing':true,'forcedJSONParsing':true,'clarifyTimeoutError':false},'adapter':['xhr','http'],'transformRequest':[null],'transformResponse':[null],'timeout':3000,'xsrfCookieName':'XSRF-TOKEN','xsrfHeaderName':'X-XSRF-TOKEN','maxContentLength':-1,'maxBodyLength':-1,'env':{},'headers':{'Accept':'application/json, text/plain, */*','Content-Type':'application/json','User-Agent':'axios/1.5.1','Content-Length':'175','Accept-Encoding':'gzip, compress, deflate, br'},'method':'post','data':'{\'icon_type\':\'none\',\'lifetime\':60000,\'model\':{\'frames\':[{\'text\':\'Post ist da\',\'icon\':\'i3551\'}],\'sound\':{\'category\':\'notifications\',\'id\':\'letter_email\',\'repeat\':1},\'cycles\':1}}','baseURL':'http://192.168.179.85:8080','url':'/api/v2/device/notifications','responseType':'json','auth':{'username':'dev','password':'xxxxxxxxxxxxx'},'httpsAgent':{'_events':{},'_eventsCount':2,'_maxListeners':100,'defaultPort':443,'protocol':'https:','options':{'rejectUnauthorized':false,'noDelay':true,'path':null},'requests':{},'sockets':{},'freeSockets':{},'keepAliveMsecs':1000,'keepAlive':false,'maxSockets':null,'maxFreeSockets':256,'scheduling':'lifo','maxTotalSockets':null,'totalSocketCount':0,'maxCachedSessions':100,'_sessionCache':{'map':{},'list':[]}}},'code':'ERR_BAD_REQUEST','status':400}
-- | -- | -- | --


`

**Comment by klein0r** [comment]
Da nach wie vor kein Debug-Log geteilt wurde, mache ich hier zu
