### ISSUE TITLE
feature request: radio starten

### ISSUE THREAD

**Issue by krobipd** [klein0r/ioBroker.lametric#16]
hallo das ist ein feature request

könntest du die Möglichkeit des radio Startens implementieren bitte

https://lametric-documentation.readthedocs.io/en/latest/reference-docs/device-apps.html

> 

Radio | com.lametric.radio | radio.play - start playbackradio.stop - stop playbackradio.next - next radio stationradio.prev - previous radio station
-- | -- | --

**Comment by klein0r** [comment]
Besser spät als nie 😄Habe ich in Version 0.0.7 hinzugefügt
