### ISSUE TITLE
Feature Request: chance device mode

### ISSUE THREAD

**Issue by krobipd** [klein0r/ioBroker.lametric#20]
Hallo

Ich bin mir zwar nicht ganz sicher ob das gehen könnte.
Aber es wäre toll via iobroker den Mode zu ändern. Meine LaMetric läuft immer im Auto Modus ich würde sie aber sehr gerne unter Umständen auf Kiosk und dann die dark App aktivieren. 

Ich habe in der api Doku nachgesehen dort steht aber nur was von get device Mode. Vl könntest du ja mal reinschauen. Wäre toll.

**Comment by klein0r** [comment]
Ich konnte leider auch nichts dazu finden. Gefühlt habe ich schon die komplette API implementiert. In der App kann man ja zwischen mehreren Modes wechseln:

- auto - **auto scroll** mode, when device switch between apps automatically
- manual - **click to scroll** mode, when user can manually switch between apps
- schedule - **apps by time schedule**
- kiosk - kiosk mode when **single app** is locked on the device

Wobei *schedule* nichtmal in der API aufgeführt ist, aber über die App konfiguriert werden kann. Da das Smartphone das alles konfigurieren kann, muss es dafür auch eine Schnittstelle geben. Allerdings ist das nicht dokumentiert.

Ich habe denen mal auf Twitter geschrieben: https://twitter.com/haus_automation/status/1321905464272064512

**Comment by klein0r** [comment]
Siehe auch https://github.com/lametric/Documentation/issues/16

**Comment by krobipd** [comment]
Vielen Dank für dein Modul und Mühen.

Ja mittlerweile hab ich mir das ganze auch etwas angesehen und musste leider feststellen das die API da teilweise doch recht mager ist. Ich konnte das für mich via blockly gut hinbiegen.

**Comment by klein0r** [comment]
Es ist wirklich schade, wie das Gerät aktuell behandelt wird. Das könnte alles so viel weiter sein...
