### ISSUE TITLE
[Bug]: icons my data

### ISSUE THREAD

**Issue by lolax80** [klein0r/ioBroker.lametric#223]
### I'm sure that

- [X] This issue is still present in the **current beta version** of this adapter
- [X] There is no other (open) issue with the same topic (use the search!)
- [X] This issue is not described in the adapter documentation / FAQ (read the docs!)

### Version of LaMetric firmware

2.3.9

### The problem

Hallo Matthias,

welche icons lassen sich denn bei my Data nutzen?
ich bekomme die Icons zb 49425 nicht gespeichert

### Version of nodejs

v18.19.1

### Version of ioBroker js-controller

5.0.19

### Version of adapter

3.04

**Comment by lolax80** [comment]
kann geschlossen werden. es lag an dem i oder a vor dem icon

**Comment by klein0r** [comment]
https://github.com/klein0r/ioBroker.lametric/blob/master/docs/de/my-data-diy.md#frame-konfiguration

https://github.com/klein0r/ioBroker.lametric/blob/0cc7195b9489cb1e5f1fbe791ac45594ab64904a/docs/de/my-data-diy.md?plain=1#L111
