### ISSUE TITLE
helligkeitswerte passen nicht

### ISSUE THREAD

**Issue by krobipd** [klein0r/ioBroker.lametric#23]
hey

da ich gerade an einem skript arbeite und mir dabei die history werte angeschaut habe. habe ich entdeckt das die helligskeitswerte nicht protokolliert werden.

dH meine lametrics laufen immer im auto modus, da eine genau unter einer led ist und sonst immer volle helligkeit macht wollte ich jetzt die helligkeit manuel regel - das funktioniert auch.

dabei habe ich aber festgestellt das wenn der auto modus läuft keine realen werte eingetragen werden sondern immer der letzte.

zB bei der einen steht IMMER 100% drin - tag und nacht jeden tag - kann nicht sein.
bei der zweiten steht immer 2 % drin - auch jeden tag, jede nacht, jede stunde (übertrieben aber jeder datensatz)

**Comment by klein0r** [comment]
Das gibt die API leider nicht her. Sobald man in "Auto" ist, wird zwar die Helligkeit automatisch angepasst, aber man bekommt keine Helligkeitswerte über die API geliefert. Im Wert "Helligkeit" steht immer der zuletzt vergebene manuelle Wert.
