### ISSUE TITLE
Feature Request: Disable DIY values by value

### ISSUE THREAD

**Issue by fichtelmann** [klein0r/ioBroker.lametric#32]
It would be nice to disable or partially remove a value from the DYI JSON if it has a special value.

E.g. If a value inside a field is 0 it's not shown on the lametric.

**Comment by sbormann** [comment]
+1
maybe add an optional datapoint for every frame (hide this frame, if datapoint is true)

**Comment by fichtelmann** [comment]
I would prefer to define a special value. E.g "no trash" 😉
But @sbormann idea additional would give more flexibility 😃
