### ISSUE TITLE
My Data (DIY) - LaMetric displays only the string, not the data value

### ISSUE THREAD

**Issue by j0hu** [klein0r/ioBroker.lametric#35]
Hello Matthias,

I'd like to show the outdoor temperature onto my LaMetric device.

Therefore I install and configure the LaMetric- and Simple API adapter exactly as shown into your youtube video :-)

After I saved my settings and restarted both adapter, my LaMetric only display the value as string/text: {hm-rpc.1.000ED709B282BC.1.ACTUAL_TEMPERATURE}, but not the value itself (for example: -1 °C) !?

Here's my config...

From my LaMetric-Adapter "My Data (DIY)" tab:

Icon         Text
i2355       {hm-rpc.1.000ED709B282BC.1.ACTUAL_TEMPERATURE} °C

My Simple API url replay this in browser:
{"frames":[{"text":"{hm-rpc.1.000ED709B282BC.1.ACTUAL_TEMPERATURE} °C","icon":"i2355"}]}

Do I something wrong? Thank's in advance

Versions:
 - LaMetric Adapter version: 1.2.0
 - Simple API Adapter version: 2.5.3
 - JS-Controller version: 3.2.16
 - Node version: 12.20.1
 - Operating system: Debian 10.8

**Comment by TschiepTschiep** [comment]
Hey,

same Problem...

LaMetric Adapter Version: 1.2.0
SimpleAPI: 2.5.2
Node.js: 12.20.1
HomeMatic RPC: 1.14.24
Sensor: Homematic Temperature Sensor

http://192.168.96.220:8087/getPlainValue/hm-rpc.0.LEQ0030029.1.TEMPERATURE
-> works fine in browser. Result "-4.4"

Lamtetric Output: "{hm-rpc.0.LEQ0030029.1.TEMPERATURE}" 

Regards,
TschiepTschiep

**Comment by DirkEickhoff** [comment]
Hi Matthias,

I'm joining with another example.

  LaMetric Adapter Version: 1.2.0
  SimpleAPI: 2.5.3
  Loxone Miniserver: 2.1.0
  Java Skript Engine Version: 5.0.14

If I want to display {loxone.0.WeatherServer.Actual.weatherType-text}
on web:
HTTP://IP:Port/getPlainValue/loxone.0.WeatherServer.Actual.weatherType-text
"raining" 
is returned correct.

Lametric displays only the frame itself: {loxone.0.WeatherServer.Actual.weatherType-text}

Other data from same loxone object is read and displayed correctly.
e.g. on frame:
{loxone.0.WeatherServer.Actual.temperature} 
Lametric displays the Value correctly. e.g. 
6.4

Thank you.

BR
Dirk

**Comment by NovalisVonHardenberg** [comment]
A known problem. There is a maximum character length.
From a certain value onwards, only the string is displayed, e.g.
✅ {0_userdata.0.Testschalter}
❌0_userdata.0.TestschalterTestschalterTestschalterTestschalterTestschalterTestschalter}

Solution:
Create your own status with a short number of characters. Create a script that writes the value from the long status to the short status.

**Comment by klein0r** [comment]
@DirkEickhoff Please check version 1.2.1 or later
@NovalisVonHardenberg Unable to reproduce the issue. There is not length limitation in regex.
