### ISSUE TITLE
Simple.api https does not work

### ISSUE THREAD

**Issue by jolu1705** [klein0r/ioBroker.lametric#36]
Hi,

as soon as I switch to HTTPS in the simple.api adapter my lametric time does not get info from the lametric adapter anymore.
Blockly notifications still can be displayed.

In the iOS app I have for sure changed the link to https://....

Same happens when I turn off HTTPS and turn on authentication.
Blockly works, but the adapter internal push stops working

Simple.api 2.5.2
Lametric 1.2.0

**Comment by klein0r** [comment]
HTTPS and certificate handling is not supported by the LaMetric (as far as I know). Not an issue of this adapter.
