### ISSUE TITLE
Warning message in iobroker Log after update to new JS Controller

### ISSUE THREAD

**Issue by martz170** [klein0r/ioBroker.lametric#37]
Hallo,

nach Umstellung auf die Beta Admin Oberfläche und update auf den JS Controller 3.3x gibt der Adapter ständig folgende Fehlermeldungen:

lametric.0 | 2021-05-03 13:36:04.923 | warn | State  value to set for  "lametric.0.meta.display.screensaver.modes.timeBased.endTime" has wrong  type "undefined" but has to be "string"
-- | -- | -- | --
lametric.0 | 2021-05-03 13:36:04.923 | warn | State  value to set for  "lametric.0.meta.display.screensaver.modes.timeBased.startTime" has  wrong type "undefined" but has to be "string"

Lt. Forum soll es an den Entwickler gemeldet werden

Siehe auch:
https://forum.iobroker.net/topic/44624/js-controller-3-3-jetzt-im-latest

Danke!

**Comment by Apollon77** [comment]
@klein0r We plan to release js-controller 3.3 to stable soon, DO you think you can find time for it soon?

**Comment by klein0r** [comment]
I am not able to reproduce this issue. @martz170 Please change log level to debug and share the response of the `device/display` api call

**Comment by martz170** [comment]
Hello,
 after starting this adapter since weeks - the warning messages have disappeared. I tried to reproduce the error with my wrong API Token ( see #39) but this message has not occured again. You can close the Ticket.
