### ISSUE TITLE
After update to 1.3.0  no connection to device or service

### ISSUE THREAD

**Issue by martz170** [klein0r/ioBroker.lametric#39]
Hallo,

nach update to Adapter Version 1.3.0 bekommt der Adapter keine Verbindung zum Device or Service.
Das Token hatte kryptische Symbole und wurde von mir erneuert, jedoch keine Besserung.

Anbei ein Debug log vom Adapter:

<html><body>

lametric.0 | 2021-05-05 16:26:21.260 | warn | received error 401 response from /api/v2/device/apps with content: {"errors":[{"message":"Authorization is required"}]}
-- | -- | -- | --
lametric.0 | 2021-05-05 16:26:21.258 | warn | received error 401 response from /api/v2/device/display with content: {"errors":[{"message":"Authorization is required"}]}
lametric.0 | 2021-05-05 16:26:21.256 | warn | received error 401 response from /api/v2/device with content: {"errors":[{"message":"Authorization is required"}]}
lametric.0 | 2021-05-05 16:26:21.248 | info | State value to set for "lametric.0.mydatadiy.obj" has to be type "string" but received type "object"
lametric.0 | 2021-05-05 16:26:21.236 | debug | My Data (DIY) frame update to []
lametric.0 | 2021-05-05 16:26:21.235 | debug | My Data (DIY) refresh output state with config []
lametric.0 | 2021-05-05 16:26:21.235 | debug | My Data (DIY) found foreign states: []
lametric.0 | 2021-05-05 16:26:21.224 | debug | My Data (DIY) found 0 dynamic states
lametric.0 | 2021-05-05 16:26:21.223 | debug | My Data (DIY) collecting states
lametric.0 | 2021-05-05 16:26:21.223 | debug | re-creating refresh app timeout
lametric.0 | 2021-05-05 16:26:21.223 | debug | sending "GET" request to "/api/v2/device/apps" with data: null
lametric.0 | 2021-05-05 16:26:21.222 | debug | re-creating refresh state timeout
lametric.0 | 2021-05-05 16:26:21.222 | debug | sending "GET" request to "/api/v2/device/display" with data: null
lametric.0 | 2021-05-05 16:26:21.221 | debug | sending "GET" request to "/api/v2/device" with data: null
lametric.0 | 2021-05-05 16:26:21.220 | debug | refreshing device state
lametric.0 | 2021-05-05 16:26:21.208 | info | starting. Version 1.3.0 in /opt/iobroker/node_modules/iobroker.lametric, node: v14.16.1, js-controller: 3.3.8
lametric.0 | 2021-05-05 16:26:21.095 | debug | Plugin sentry Initialize Plugin (enabled=true)

</body>
</html>

**Comment by klein0r** [comment]
You have to re-enter the api key (since the information will be stored encrypted)

**Comment by martz170** [comment]
Yes, wrong copy and paste from me - there is a very small blank caracter at the end of the Token that causes the error.

**Comment by klein0r** [comment]
Ah, good to know! I will add a trim() to remove white spaces in the user configuration to avoid that
