### ISSUE TITLE
Do you plan to place it into repository?

### ISSUE THREAD

**Issue by GermanBluefox** [klein0r/ioBroker.lametric#4]

**Comment by steckenpferd** [comment]
Will it become a stable version

**Comment by siggi85** [comment]
I am planning to get a lametric and want use it much with iobroker. Would love to see a stable version in repository. :)

**Comment by steckenpferd** [comment]
Matthias would be nice if you could push it to IoBroker repository or to iobroker-community-adapters

**Comment by klein0r** [comment]
Just pushed a new version with a lot of fixes to the iobroker repositories.
