### ISSUE TITLE
Error 400 response in automatic screensaver mode when info messages are sent

### ISSUE THREAD

**Issue by tmycgn** [klein0r/ioBroker.lametric#43]
When Lametric is currently in automatic screensaver mode, sent info messages always result with warning: 

_received error 400 response from /api/v2/device/notifications with content: {"errors":[{"message":"Only notifications with priority 'critical' are allowed in current mode"}]}_

The reason for this is the LaMetric API:
https://lametric-documentation.readthedocs.io/en/latest/reference-docs/device-notifications.html

> This notification will not be shown when screensaver is active.

However, it would be nice if you could query the current status of whether the screensaver is active in auto mode to avoid these warnings. Another option would be to not forward the message to the device at all.

**Versions:**  
- Node.js v12.22.1
- NPM 6.14.12
- JS-Controller 3.3.11
- Plattform: linux
- ioBroker: v5.1.7

**Comment by klein0r** [comment]
I think the current behaviour is not that bad. You do something which is not intended by the LaMetric and you get feedback as an error whats wrong. When I will filter the notification automatically, I will get new issues that some messages are lost without any errors.

**Comment by tmycgn** [comment]
Understandable. Would it be possible to add a property that indicates if the screensaver is currently on? For _timeBased_ this already exists, for _whenDark_ this does not exist yet as far as I can see?

**Comment by klein0r** [comment]
As far as i know, there is no way to request if the screensaver is active right now.

**Comment by tmycgn** [comment]
Ok too bad, that's what I guessed. Then we could close the ticket. Thanks for checking that!
