### ISSUE TITLE
Type issue with js-controller 3.3

### ISSUE THREAD

**Issue by ahnungsbefreit** [klein0r/ioBroker.lametric#45]
With update to js-controller 3.3 I get periodically several error messages from lametric 1.3.2 like this:

` State value to set for "lametric.0.mydatadiy.obj" has to be type "string" but received type "object"`

**Comment by marlan99** [comment]
yes, same here. also on 1.3.2 with the same Logentry

**Comment by ahnungsbefreit** [comment]
Any progress on this one?

**Comment by klein0r** [comment]
It is not that easy to fix, because (if I follow the rules) the LaMetric Time won't be able to parse the information correctly. See linked issue in https://github.com/ioBroker/ioBroker.simple-api/issues/96 for more technical details

**Comment by klein0r** [comment]
The fix is pretty simple. See commit https://github.com/klein0r/ioBroker.lametric/commit/f43858fb98c4fae48910eb1fd59b8148ee1465cb

But... I have to wait until the simple api adapter is able to return the information correctly

**Comment by klein0r** [comment]
Das ist in Version 1.5.0 gefixt. Dafür braucht ihr aber 2 Dinge

- Simple API Adapter mindestens in Version 2.6.2
- Den Parameter `?json` an der Url um den Wert im richtigen Format abzurufen.

**Falls ihr eines von beiden nicht macht, läuft myData DIY nicht mehr!**
