### ISSUE TITLE
Eigene Datenpunkte werden via DIY nicht angezeigt

### ISSUE THREAD

**Issue by tccflash** [klein0r/ioBroker.lametric#49]
Hi, ich habe via DIY schon einiges im Adapter eingetragen und alles funktioniert wunderbar.

Sobald ich allerdings etwas aus meinen eigenen Datenpunkten in DIY im Adapter Einträge, zeigt es nur den Pfad auf der Lametric Time an. In meinem Beispiel läuft dann immer: {0_userdata.0.Gerãte.Crypto.IOTAEUR} durch, anstatt der Zahlenwert.

Egal welchen Datenpunkt aus 0_userdata.0 ich wähle, passiert immer das gleiche. Sobald ich einen anderen Datenpunkt Einträge, wird dieser komplett ausgelesen und angezeigt.

**Comment by klein0r** [comment]
Ah, ich sehe schon. Das liegt an Deinem Datenpunkt. `Gerãte`. Ich "suche" momentan nur nach bestimmten Zeichen um einen Datenpunkt zum ersetzen zu identifizieren. Das `ã` ist wohl nicht dabei. Warum heißt der so komisch?

**Comment by tccflash** [comment]
Hi... Sorry das war Autokorrektur. Mein Ordner heißt natürlich "Geräte".
