### ISSUE TITLE
"verstecke Wert wenn" funktioniert nicht?

### ISSUE THREAD

**Issue by ic14m001** [klein0r/ioBroker.lametric#53]
### The problem

Hallo Matthias! Bin begeisterter Nutzer/Abonnent/Kunde von hausautomatisierung.com und nutze Deinen Adapter in IOBroker für die Lametric. Ich zeige mir diverseste Werte auf der Lametric an, darunter auch den aktueller Ertrag der PV-Anlage. Dieser ist aber dann am Abend natürlich "0", deshalb möchte ich mir den Werte auch ausblenden lassen. Jedoch egal was ich in der Spalte "verstecke Wert wenn" eintrage wird immer dann der "0"-Wert angezeigt ... Mach ich was falsch? In der Doku steht zu dem PUnkt leider nichts ...
BG
David

### Version of nodejs

14.1

### Version of ioBroker js-controller

3.3.2

### Version of Adapter

1.5.2

### Operating system running ioBroker

Debian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Der Wert wird quasi ignoriert, wenn er mit dem Wert in der Spalte übereinstimmt. Aber komplett, weil man ja auch mehrere Platzhalter verwenden könnte.

Also wenn Du sagst: ```Außentemperatur {pfad.zur.id.der.temperatur}°C```, dann kannst Du das ausblenden, wenn der Wert z.B. ```Außentemperatur 1°C``` ist. Dort muss also der komplette Text rein, welcher sich ergibt.

**Comment by ic14m001** [comment]
Dankeschön, funktioniert jetzt 🤗War für mich aus der Doku nicht ganz ersichtlich ....Schönes Wochenende!BG DavidVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matthias Kleine ***@***.***> Datum: 18.02.22  17:44  (GMT+01:00) An: "klein0r/ioBroker.lametric" ***@***.***> Cc: ic14m001 ***@***.***>, State change ***@***.***> Betreff: Re: [klein0r/ioBroker.lametric] "verstecke Wert wenn" funktioniert nicht? (Issue #53) 

Der Wert wird quasi ignoriert, wenn er mit dem Wert in der Spalte übereinstimmt. Aber komplett, weil man ja auch mehrere Platzhalter verwenden könnte.

Also wenn Du sagst: Außentemperatur {pfad.zur.id.der.temperatur}°C, dann kannst Du das ausblenden, wenn der Wert z.B. Außentemperatur 1°C ist. Dort muss also der komplette Text rein, welcher sich ergibt.

**Comment by klein0r** [comment]
Dann würde ich dich bitten, das kurz (gerne zweisprachig) zu dokumentieren. Gerne einen Pull-Request erstellen oder den Text hier in den Issue packen, dann ergänze ich das in der Doku.

**Comment by klein0r** [comment]
❓

**Comment by ic14m001** [comment]
Hallo! Du hast ja beim Issue schon den Lösungstext hinzugefügt, muss ich da jetzt noch was machen?BG DavidVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Matthias Kleine ***@***.***> Datum: 21.02.22  16:31  (GMT+01:00) An: "klein0r/ioBroker.lametric" ***@***.***> Cc: ic14m001 ***@***.***>, State change ***@***.***> Betreff: Re: [klein0r/ioBroker.lametric] "verstecke Wert wenn" funktioniert nicht? (Issue #53) 

❓

**Comment by klein0r** [comment]
Naja, das kann ich ja schlecht so in die Doku einfügen. Ich mach hier mal zu. Dann bleibt es halt so 😄
