### ISSUE TITLE
LaMetric Time does not show data

### ISSUE THREAD

**Issue by west89** [klein0r/ioBroker.lametric#60]
### The problem

LaMetric Time does not show the data it fetches from ioBroker from mydatadiy.obj.
In Browser the data is displayed to me.

### Version of nodejs

14.19.1

### Version of ioBroker js-controller

6.14.16

### Version of Adapter

1.6.0

### Operating system running ioBroker

Linux (Raspberry Pi 4)

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads
![LaMetric](https://user-images.githubusercontent.com/42120960/167307256-9bc1631c-5ac1-4cf3-a592-9984567d259a.PNG)

**Comment by west89** [comment]
Error found by yourself.
With the SimpleAPI /?json was missing

**Comment by klein0r** [comment]
Everything is documented here: https://github.com/klein0r/ioBroker.lametric/blob/master/docs/de/my-data-diy.md
