### ISSUE TITLE
Konfiguration des Adapters nach Update auf 2.0.0 nicht möglich - Fehler Admin 5 erwartet

### ISSUE THREAD

**Issue by roadie33** [klein0r/ioBroker.lametric#61]
### The problem

Nach dem Update des Adapters auf 2.0.0 erscheint auf der Konfigurationsseite folgende Fehlermeldung:
"**This adapter version has no support for "Admin 4" configuration. Please switch to "Admin 5" UI or downgrade to an older version (see changelog for details).** "

Installiert sind:
Admin 5.3.8
JS Controller 4.0.23
Node.js v14.9.3
npm 6.14.17

### Version of nodejs

14.9.3

### Version of ioBroker js-controller

4.0.23

### Version of Adapter

2.0.0

### Operating system running ioBroker

 Raspbian GNU/Linux 10

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment]
Was ist an der Meldung denn nicht zu verstehen? Du hast in der Admin Konfiguration angegeben, dass Du die alte Benutzeroberfläche nutzen möchtest (vom Admin 4). Gerne einen Vorschlag machen, was da stehen müsste damit es verständlicher ist.
